server:
  servlet:
    session:
      timeout: 1800


spring:
  profiles:
    active: local
  session:
    jdbc:
      initialize-schema: embedded
    store-type: jdbc

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
