server:
  servlet:
    session:
      timeout: 1800

spring:
  profiles:
    active: local
  session:
    jdbc:
      initialize-schema: embedded
    store-type: jdbc

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  configuration:
    jdbc-type-for-null: "null"
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:sqlMap/**/*Mapper.xml
